apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hjguosr2e-go 
  janus-idp.io/tekton: hjguosr2e-go
  backstage.io/kubernetes-id: hjguosr2e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hjguosr2e-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml