apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hjguosr2e-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:16ab2c6050ea3e18a50f10745984a9cd8d9c8565@sha256:e62458ebf394e6f55667ac46a09f4715fac7451e172e3835e2b56d4ec21f7e55
          name: container-image
